# Generated by Django 3.0.3 on 2020-04-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userDetails',
        ),
    ]
