# Generated by Django 3.0.3 on 2020-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonation', '0003_donardetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donardetails',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
