# Generated by Django 3.0.3 on 2020-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonation', '0004_auto_20200423_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='donardetails',
            name='availiability_status',
            field=models.CharField(default='YES', max_length=3),
            preserve_default=False,
        ),
    ]
